version: 1.0.0.{build}
os: Visual Studio 2015 RC
environment:
  Major: 1
  Minor: 0
  Revision: 0
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
configuration: Release
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: minimal
test: off
artifacts:
- path: Build\*.nupkg
deploy:
- provider: Environment
  name: MyGet