version: 1.2.0.{build}
os: Visual Studio 2015
environment:
  Major: 1
  Minor: 2
  Revision: 0
install:
configuration: Release
before_build:
- .\bootstrap.cmd
build:
  project: master.proj
  verbosity: minimal
test: off
artifacts:
- path: Build\*.nupkg
deploy:
- provider: Environment
  name: MyGet