version: 6.0.0.{build}
os: Visual Studio 2017
environment:
  ASPNETCORE_ENVIRONMENT: appveyor
  COVERALLS_REPO_TOKEN:
    secure: vesxKEf1tMzmDCFKpU6UewVlXyXE8QdwJpKP01J/wurGmD6W/RiZd//M4V71g72Y

init:
  - git config --global core.autocrlf input

dotnet_csproj:
  patch: true
  file: 'build\version.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

configuration: Release

before_build:
  - dotnet tool install --global coveralls.net

build_script:
  - dotnet pack FluentRest.sln --configuration Release --include-symbols --include-source 

test_script:
  - dotnet test FluentRest.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

artifacts:
- path: artifacts\*.nupkg
  name: Packages

deploy:
- provider: Environment
  name: MyGet